version: '3'
services:
  backend:
    build: backend
    ports:
      - "5001:5001"
    volumes:
      - /Users/jacknely/Apps/covid19/backend:/opt
    environment:
      - MONGODB_HOST=db
      - FLASK_APP=run.py
      - FLASK_ENV=development
    links:
      - db

  frontend:
    build: frontend
    ports:
      - "5000:5000"
    volumes:
      - /Users/jacknely/Apps/covid19/frontend:/opt
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    links:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
        - "80:80"

  db:
    image: mongo:3.4
    command: mongod
